# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:8.0

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Check whether signedoff
          command: |
            echo hello world
            IS_SIGNEDOFF=`git log -1 --pretty=%B`
            echo hello world2
            CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
            echo ${CURRENT_BRANCH} xxxxx ${IS_SIGNEDOFF}
            if [ "${CURRENT_BRANCH}" = "develop" ]; then
              echo "Checking whether signed"
              if [ ! -z "${IS_SIGNEDOFF}" ]; then
                echo "Commit is signedoff"
              else
                echo "Commit is not signedoff"
              fi
            fi

      - run: cd public-interface; npm install

      # run tests!
      - run: cd public-interface;  node_modules/grunt-cli/bin/grunt build-api
